### ISSUE TITLE
Error output differs when using compiled-tools vs installed-tools.

### ISSUE THREAD

**Issue by XAMPPRocky** [EmbarkStudios/spirv-tools-rs#19]
**Describe the bug**
Depending on whether you're using `use-compiled-tools` or `use-installed-tools` you will get different output in an error message. Namely you will get `internal error` when using compiled and `invalid binary` when using installed. This an issue for Rust GPU because we now have UI tests for testing our error messages, and this difference prevents us from using installed tools on CI while using compiled tools locally as the error message output will differ which causes CI to fail.

**To Reproduce**
Change the default from `use-compiled-tools` to `use-installed-tools` in `rust-gpu` and run `cargo compiletest`.

**Expected behavior**
The error output is the same across these two features.

**Output**
```
 error: pointer has non-null integer address
   |
   = note: Stack:
           allocate_const_scalar::main
           Unnamed function ID %9

-error: invalid binary:0:0 - No OpEntryPoint instruction was found. This is only allowed if the Linkage capability is being used.
+error: internal error:0:0 - No OpEntryPoint instruction was found. This is only allowed if the Linkage capability is being used.
   |
   = note: spirv-val failed
   = note: module `$TEST_BUILD_DIR/lang/core/ptr/allocate_const_scalar.stage-id.spv`

 error: aborting due to 2 previous errors
```

**Comment by Jake-Shadle** [comment]
The change is now available in the 0.6.0 release. :slightly_smiling_face:
