### ISSUE TITLE
Detect and error helpfully when neither `use-installed-tools` or `use-compiled-tools` are enabled on rustc_codegen_spirv

### ISSUE THREAD

**Issue by termhn** [EmbarkStudios/spirv-tools-rs#3]
Right now, we get a fairly unhelpful error originating within the spirv-tools crate that is actually caused by neither of these features being enabled. Should be possible to do a

```rust
#[cfg(none(feature = "use-installed-tools", feature = "use-compiled-tools"))]
error!("Enable one of the `use-compiled-tools` or `use-installed-tools` features");
```
or something to that effect

**Comment by khyperia** [comment]
The relevant code for the error message @termhn discussed is in `spirv-tools-rs`, so, transferred it here.
