### ISSUE TITLE
Fails to build under macOS due to sprintf warning

### ISSUE THREAD

**Issue by rsammelson** [EmbarkStudios/spirv-tools-rs#34]
**Describe the bug**
On macOS, sprintf generates warnings that lead to compiler errors due to the Werror option, despite any flags given to try to negate the warning.

**Expected behavior**
Either Werror should be removed, or sprintf changed to snprintf to eliminate warnings.

**Device:**
 - OS: macOS 13
 - Compiler: "Apple clang version 14.0.0 (clang-1400.0.29.102)"
 - Target: arm64-apple-darwin22.1.0

**Comment by repi** [comment]
This was fixed in #32
